threading to close dut session fix 3 issues: bug#1 Traceback (most recent call last):   File "C:\Python27\Lib\threading.py", line 801, in __bootstrap_inner     self.run()   File "C:\Python27\Lib\threading.py", line 754, in run     self.__target(*self.__args, **self.__kwargs)   File "C:/workspace/gDasH\gui\SessionTab.py", line 125, in update_output     wx.CallAfter(self.output_window.SetDefaultStyle,wx.TextAttr(wx.GREEN,  wx.BLACK,font =wx.Font(self.font_point, family = wx.DEFAULT, style = wx.NORMAL, weight = wx.NORMAL, faceName = 'Consolas')))   File "C:\Python27\lib\site-packages\wx-3.0-msw\wx\_core.py", line 16711, in __getattr__     raise PyDeadObjectError(self.attrStr % self._name) PyDeadObjectError: The C++ part of the TextCtrl object has been deleted, attribute access no longer allowed. Bug#2 	  File "C:/workspace/gDasH\lib\dut.py", line 417, in close_session 	    self.write_locker.release() 	AttributeError: 'NoneType' object has no attribute 'release'
bug#3
	  File "C:/workspace/gDasH\lib\dut.py", line 402, in close_session
	    error('dut({}): {}'.format(self.name, e))
	  File "C:\Python27\lib\site-packages\wx-3.0-msw\wx\_core.py", line 16711, in __getattr__
	    raise PyDeadObjectError(self.attrStr % self._name)
	PyDeadObjectError: The C++ part of the SessionTab object has been deleted, attribute access no longer allowed	ERRO	dut.py:472	read_data:The C++ part of the SessionTab object has been deleted, attribute access no longer allowed.